[package]
name = "shux"
version = "0.1.0"
edition = "2021"

[dependencies]
bon = "2.3.0"
close_fds = "0.3.2"
crossbeam = "0.8.4"
crossterm = "0.28.1"
nix = { version = "0.29.0", features = ["term"] }
ratatui = "0.28.1"
